name: Barcode CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core 5.0.103
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.103
    - name: Setup .NET Core 3.1.404
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.404
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build BarcodeStandard/BarcodeStandard.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test
